#!/bin/bash

# Special test script which will always fail to update dns

token=${DUCKDNS_TOKEN:-}

if [ -z "$token" ]; then
    echo "DUCKDNS_TOKEN not set"
    exit 1
fi

domain="$1"

response=$(curl --retry 5 --silent "https://www.duckdns.org/update?domains=${domain}&token=${token}&txt=FAIL")
if [ "$response" != "OK" ]; then
    echo "Failed to update TXT record for ${domain} at duckdns.org (is the TOKEN valid?)"
    echo "Response: $response"
    exit 1
fi
