FROM alpine:latest

RUN apk --no-cache add supervisor openssl git curl bind-tools wget gawk nginx bash
# RUN apk --no-cache add vim dos2unix # for debugging

WORKDIR /root
RUN mkdir /run/nginx
RUN mkdir /etc/nginx/pki
RUN mkdir /etc/nginx/pki/private
COPY ./test/test-config/nginx-ubuntu-no-ssl /etc/nginx/sites-enabled/default
COPY ./test/alpine-supervisord.conf /etc/supervisord.conf

# BATS (Bash Automated Testings)
RUN git clone https://github.com/bats-core/bats-core.git /bats-core
RUN git clone https://github.com/jasonkarns/bats-support /bats-support
RUN git clone https://github.com/jasonkarns/bats-assert-1 /bats-assert
RUN /bats-core/install.sh /usr/local

# Use supervisord to run nginx in the background
ENTRYPOINT /usr/bin/supervisord -c /etc/supervisord.conf
