FROM ubuntu:latest

# Note this image uses mawk1.3

# Set noninteractive otherwise tzdata hangs
ENV DEBIAN_FRONTEND noninteractive

# Ensure tests in this image use the staging server
ENV staging "true"
ENV DUCKDNS_TOKEN 1d616aa9-b8e4-4bb4-b312-3289de82badb

# Update and install required software
RUN apt-get update --fix-missing
RUN apt-get install -y git curl dnsutils wget nginx-light
RUN apt-get install -y vim dos2unix # for debugging
# TODO test with drill, dig, host

WORKDIR /root

# Prevent "Can't load /root/.rnd into RNG" error from openssl
RUN touch /root/.rnd

# BATS (Bash Automated Testings)
RUN git clone https://github.com/bats-core/bats-core.git /bats-core
RUN git clone https://github.com/bats-core/bats-support /bats-support
RUN git clone https://github.com/bats-core/bats-assert /bats-assert
RUN /bats-core/install.sh /usr/local

# Run eternal loop - for testing
CMD tail -f /dev/null
