#!/usr/bin/env bash

if [ "$GETSSL_OS" = "alpine" ]; then
    killall -HUP nginx >&3-
    sleep 5
elif [ "$GETSSL_OS" == "centos7" ]; then
    pgrep nginx | head -1 | xargs kill -HUP
    sleep 5
else
    service nginx restart >/dev/null >&3-
fi
