#!/usr/bin/env bash

if [ "$GETSSL_OS" = "alpine" ]; then
    killall -HUP vsftpd >&3-
elif [[ "$GETSSL_OS" == "centos"[78] || "$GETSSL_OS" == "rockylinux"* ]]; then
    pgrep vsftpd | head -1 | xargs kill -HUP
elif [[ "$GETSSL_OS" == "centos6" ]]; then
    service vsftpd restart >&3- >/dev/null
else
    service vsftpd restart >/dev/null >&3-
fi
