language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

env:
  global:
    - CF_DOMAIN=test.org
    - CF_EMAIL=getssl_test_account@mailinator.com
    - CF_KEY=845830354648e4317e1541002f4b778d07b41

before_script:
  - wget -O test/assert.sh https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh
  - chmod +x test/assert.sh
  - curl -X POST 'https://api.cloudflare.com/client/v4/zones' -H "X-Auth-Email:\ $CF_EMAIL" -H "X-Auth-Key:\ $CF_KEY" -H "Content-Type:\ application/json" --data "{\"name\":\"$CF_DOMAIN\",\"jump_start\":false}"

script:
  - shellcheck getssl
  - shellcheck dns_scripts/dns_add_cloudflare
  - shellcheck dns_scripts/dns_del_cloudflare
  - cd test && ./test.sh
  
matrix:
  fast_finish: true
