version: 2
jobs:
  build:
    docker:
      # This image is based on Alpine 3.7, with Shellcheck v0.4.7 and bats-core commit b1da565 (2017-11-13)
      # Shellcheck is from base image koalaman/shellcheck-alpine:v0.4.7
      # bats-core is from GitHub repo, see Dockerfile.dev in project root for build environment
      - image: djschaper/circleci:1.2-alpine3.7scb
    environment:
      - CIRCLE_BRANCH: integration/circleci
    shell: /bin/ash
    working_directory: /srv/getsslD
    steps:
      - run:
          name: Install Run Dependencies
          command: |
            apk add --no-cache --virtual .run-deps \
            curl \
            drill \
            openssl
      - checkout
      - run:
          name: Copy getsslD to path'd directory
          command: cp /srv/getsslD/getsslD /bin/
      - run:
          name: Test initial script run
          command: getsslD --help
      - run:
          name: Shellcheck getsslD
          command: shellcheck /srv/getsslD/getsslD
      - run:
          name: Check for bats executable
          command: bats -h
