#!/bin/bash

echo "In the DNS, a new TXT record needs to be created for;"
echo "_acme-challenge.${1}"
echo "containing the following value"
echo "$2"

read -r -p "Press any key to obtain the certificate once the records have been updated..."
