#!/bin/bash

# example of script to add token to local dns using nsupdate

dnskeyfile="path/to/bla.key"

fulldomain="$1"
token="$2"

printf "update add _acme-challenge.%s. 300 in TXT \"%s\"\n\n" "${fulldomain}" "${token}" | nsupdate -k "${dnskeyfile}" -v
