name: Run all tests DEBUG
on:
  workflow_dispatch:
    branches:
      - master
      - acme-dns
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Check running containers
        run: docker ps
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v1
