name: Run all tests on pebble
on:
  push:
    paths-ignore:
      - '.github/workflows/*'
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
jobs:
  test-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Run test suite on Alpine
        run: test/run-test.sh alpine
  test-bash-4-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Run test suite on Alpine using Bash 4.0
        run: test/run-test.sh bash4-0
  test-bash-4-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Run test suite on Alpine using Bash 4.2
        run: test/run-test.sh bash4-2
  test-bash-5-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Run test suite on Alpine using Bash 5
        run: test/run-test.sh bash5-0
  test-centos6:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Build the docker-compose stack
          run: docker-compose up -d --build
        - name: Run test suite on CentOS6
          run: test/run-test.sh centos6
  test-centos7:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Build the docker-compose stack
          run: docker-compose up -d --build
        - name: Run test suite on CentOS7
          run: test/run-test.sh centos7
  test-centos8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Run test suite on CentOS8
        run: test/run-test.sh centos8
  test-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Run test suite on Debian
        run: test/run-test.sh debian
  test-rockylinux8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Run test suite on RockyLinux8
        run: test/run-test.sh rockylinux8
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Run test suite on Ubuntu
        run: test/run-test.sh ubuntu
  test-ubuntu16:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Run test suite on Ubuntu16
        run: test/run-test.sh ubuntu16
  test-ubuntu18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Run test suite on Ubuntu18
        run: test/run-test.sh ubuntu18
