name: Run tests against Staging server using Dynu
on:
  workflow_dispatch
env:
  DYNU_API_KEY: ${{ secrets.DYNU_API_KEY == '' && '65cXefd35XbYf36546eg5dYcZT6X52Y2' || secrets.DYNU_API_KEY }}
jobs:
  test-centos7-dynu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: test/Dockerfile-centos7-dynu
          tags: getssl-centos7-dynu
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build the docker compose stack
        run: docker compose up -d --build
      - name: Run test suite on CentOS7 against Staging using Dynu
        run: test/run-test.sh centos7-dynu
  test-ubuntu-dynu:
    runs-on: ubuntu-latest
    if: always()
    needs: test-centos7-dynu
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build test image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: test/Dockerfile-ubuntu-dynu
          tags: getssl-ubuntu-dynu
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build the docker compose stack
        run: docker compose up -d --build
      - name: Run test suite on Ubuntu against Staging using Dynu
        run: test/run-test.sh ubuntu-dynu
