name: Run all tests using Dynu and acmedns
on:
  push:
    paths-ignore:
      - '.github/workflows/*'
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
env:
  DYNU_API_KEY: ${{ secrets.DYNU_API_KEY == '' && '65cXefd35XbYf36546eg5dYcZT6X52Y2' || secrets.DYNU_API_KEY }}
jobs:
  test-ubuntu-acmedns:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker-compose stack
        run: docker-compose up -d --build
      - name: Run test suite on Ubuntu against Staging using acmedns
        run: test/run-test.sh ubuntu-acmedns
